export enum SYSTEM_CODE {
	SUCCESS = 'SUCCESS',
	FAILED = 'FAILED',
	TIMEOUT = 'TIMEOUT',
	SORRY_SOMETHING_WENT_WRONG = 'SORRY_SOMETHING_WENT_WRONG',
	PLEASE_THROW_SYSTEM_CODE = 'PLEASE_THROW_SYSTEM_CODE',
	BAD_REQUEST = 'BAD_REQUEST',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	INVALID_USER_INFO = 'INVALID_USER_INFO',
	USER_EXIST = 'USER_EXIST',
}
